openapi: 3.0.3
info:
  title: ContosoShop Orders API
  description: REST API for managing customer orders in the ContosoShop E-commerce Support Portal
  version: 1.0.0
  contact:
    name: ContosoShop Support
    email: support@contososhop.com

servers:
  - url: https://localhost:5001/api
    description: Local development server
  - url: https://contososhop-api.azurewebsites.net/api
    description: Production Azure App Service

tags:
  - name: Orders
    description: Order management operations

paths:
  /orders:
    get:
      tags:
        - Orders
      summary: Get all orders for current user
      description: Returns a list of all orders belonging to the authenticated user, sorted by order date descending
      operationId: getOrders
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderSummary'
              examples:
                multipleOrders:
                  summary: User with multiple orders
                  value:
                    - id: 1001
                      orderDate: '2026-01-05T10:30:00Z'
                      status: 'Delivered'
                      totalAmount: 59.99
                      itemCount: 2
                    - id: 1002
                      orderDate: '2026-01-25T14:20:00Z'
                      status: 'Shipped'
                      totalAmount: 15.00
                      itemCount: 1
                emptyOrders:
                  summary: User with no orders
                  value: []
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /orders/{id}:
    get:
      tags:
        - Orders
      summary: Get order details by ID
      description: Returns complete order information including all items, dates, and status
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          description: Order ID
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetails'
              examples:
                deliveredOrder:
                  summary: Delivered order (returnable)
                  value:
                    id: 1001
                    userId: 1
                    orderDate: '2026-01-05T10:30:00Z'
                    status: 'Delivered'
                    totalAmount: 59.99
                    shipDate: '2026-01-06T08:00:00Z'
                    deliveryDate: '2026-01-12T15:30:00Z'
                    items:
                      - id: 1
                        productName: 'Wireless Mouse'
                        quantity: 1
                        price: 25.00
                      - id: 2
                        productName: 'Keyboard'
                        quantity: 1
                        price: 34.99
        '404':
          description: Order not found or does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: 'https://tools.ietf.org/html/rfc7231#section-6.5.4'
                title: 'Not Found'
                status: 404
                detail: 'Order with ID 1001 not found or does not belong to the current user'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /orders/{id}/return:
    post:
      tags:
        - Orders
      summary: Initiate return for delivered order
      description: Processes a return request for an order with Delivered status. Changes order status to Returned and initiates refund process.
      operationId: returnOrder
      parameters:
        - name: id
          in: path
          description: Order ID to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: Return processed successfully
        '400':
          description: Bad request - order cannot be returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              examples:
                notDelivered:
                  summary: Order not yet delivered
                  value:
                    type: 'https://tools.ietf.org/html/rfc7231#section-6.5.1'
                    title: 'Bad Request'
                    status: 400
                    detail: 'Order 1002 cannot be returned. Only delivered orders are eligible for return.'
                alreadyReturned:
                  summary: Order already returned
                  value:
                    type: 'https://tools.ietf.org/html/rfc7231#section-6.5.1'
                    title: 'Bad Request'
                    status: 400
                    detail: 'Order 1004 has already been returned.'
        '404':
          description: Order not found or does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  schemas:
    OrderSummary:
      type: object
      description: Summary view of an order for list display
      required:
        - id
        - orderDate
        - status
        - totalAmount
        - itemCount
      properties:
        id:
          type: integer
          format: int32
          description: Unique order identifier
          example: 1001
        orderDate:
          type: string
          format: date-time
          description: Date and time when order was placed (UTC)
          example: '2026-01-05T10:30:00Z'
        status:
          type: string
          enum: [Processing, Shipped, Delivered, Returned]
          description: Current order status
          example: 'Delivered'
        totalAmount:
          type: number
          format: decimal
          description: Total order value in USD
          example: 59.99
        itemCount:
          type: integer
          format: int32
          description: Number of items in order
          example: 2

    OrderDetails:
      type: object
      description: Complete order information including all items
      required:
        - id
        - userId
        - orderDate
        - status
        - totalAmount
        - items
      properties:
        id:
          type: integer
          format: int32
          description: Unique order identifier
          example: 1001
        userId:
          type: integer
          format: int32
          description: User who owns this order
          example: 1
        orderDate:
          type: string
          format: date-time
          description: Date and time when order was placed (UTC)
          example: '2026-01-05T10:30:00Z'
        status:
          type: string
          enum: [Processing, Shipped, Delivered, Returned]
          description: Current order status
          example: 'Delivered'
        totalAmount:
          type: number
          format: decimal
          description: Total order value in USD
          example: 59.99
        shipDate:
          type: string
          format: date-time
          nullable: true
          description: Date and time when order was shipped (UTC), null if not yet shipped
          example: '2026-01-06T08:00:00Z'
        deliveryDate:
          type: string
          format: date-time
          nullable: true
          description: Date and time when order was delivered (UTC), null if not yet delivered
          example: '2026-01-12T15:30:00Z'
        items:
          type: array
          description: Line items in this order
          items:
            $ref: '#/components/schemas/OrderItem'

    OrderItem:
      type: object
      description: Individual product line item within an order
      required:
        - id
        - productName
        - quantity
        - price
      properties:
        id:
          type: integer
          format: int32
          description: Unique item identifier
          example: 1
        productName:
          type: string
          maxLength: 200
          description: Name of the product
          example: 'Wireless Mouse'
        quantity:
          type: integer
          format: int32
          minimum: 1
          description: Number of units purchased
          example: 1
        price:
          type: number
          format: decimal
          description: Unit price in USD at time of purchase
          example: 25.00

    ProblemDetails:
      type: object
      description: RFC 7807 Problem Details for HTTP APIs
      properties:
        type:
          type: string
          description: URI reference that identifies the problem type
          example: 'https://tools.ietf.org/html/rfc7231#section-6.5.4'
        title:
          type: string
          description: Short, human-readable summary of the problem
          example: 'Not Found'
        status:
          type: integer
          format: int32
          description: HTTP status code
          example: 404
        detail:
          type: string
          description: Human-readable explanation specific to this occurrence
          example: 'Order with ID 1001 not found or does not belong to the current user'
        instance:
          type: string
          description: URI reference identifying the specific occurrence
          example: '/api/orders/1001'

  securitySchemes:
    # Placeholder for future authentication
    # For MVP, simplified single-user demo mode
    # Production will use Azure AD B2C or similar
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT-based authentication (not implemented in MVP).
        Future production deployment will require Bearer token.

security: []  # No security for MVP demo
